// Generated by CoffeeScript 1.4.0
(function() {
  var $, get_fulltip, _fulltip;

  $ = jQuery;

  _fulltip = function(_self, option) {
    this.self = $(_self);
    $.extend(this, option);
    return this;
  };

  _fulltip.prototype = $.extend({}, $.fn.tip.constructor.prototype, {
    get_content: function() {
      return this.content || this.self.attr('data-content');
    },
    set_content: function() {
      var _this = this;
      $('.fulltip', this.el).width(this.width);
      $('.title', this.el).html(this.get_title());
      $('.content', this.el).html(this.get_content());
      return $('.close', this.el).rebind('click', function() {
        return _this.leave();
      });
    },
    get_title: function() {
      return this.title || this.self.attr('data-title');
    },
    change: function(v) {
      this.content = v.content;
      this.title = v.title;
      return this;
    }
  });

  get_fulltip = function(_self, options) {
    return $(_self).wrapData(options.cache_key, function() {
      return new _fulltip(this, options);
    });
  };

  $.fn.fulltip = function(option) {
    var binder, options;
    if (option == null) {
      option = {};
    }
    options = typeof option === 'object' && option;
    options = $.extend({}, $.fn.fulltip.defaults, options || {});
    if (typeof option === 'object') {
      binder = options.live ? "live" : "bind";
      this[binder](options.trigger, function() {
        get_fulltip(this, options).toggle();
        return false;
      });
    } else {
      if (arguments[1] != null) {
        options.title = arguments[1];
      }
      this.each(function() {
        if ({
          "enter": true,
          "leave": true,
          "toggle": true
        }[option]) {
          return get_fulltip(this, options)[option]();
        } else {
          options.content = option;
          return get_fulltip(this, options).change(options).toggle();
        }
      });
    }
    return this;
  };

  $.fn.fulltip.defaults = $.extend({}, $.fn.tip.defaults, {
    title: "Tip",
    position: "top",
    arrow: 10,
    width: 200,
    cache_key: "fulltip",
    trigger: "click",
    template: "<div class=\"fulltip-outer\">\n  <div class=\"fulltip\">\n    <a class=\"close\">&times;</a>\n    <div class=\"title\"></div>\n    <div class=\"content\"></div>\n  <div>\n</div>"
  });

}).call(this);
