// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    $('.js-menu').menu();
    return $('.form.small input').on('keyup', function() {
      var label;
      label = $(this).parent().prev();
      if (/^\s*$/.test(this.value)) {
        return label.show();
      } else {
        return label.hide();
      }
    });
  });

}).call(this);
