// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    var input_label, text_area_blur, text_area_key_up;
    input_label = function() {
      var label;
      label = $(this).parent().prev();
      if (/^\s*$/.test(this.value)) {
        return label.show();
      } else {
        return label.hide();
      }
    };
    text_area_key_up = function(event) {
      var button;
      event = event || window.event;
      button = $(this).next();
      if (event.keyCode === 13 && event.ctrlKey) {
        button.click();
      }
      if (/^\s*$/.test(this.value)) {
        if (!button.hasClass('disabled')) {
          return button.addClass('disabled');
        }
      } else {
        return button.removeClass('disabled');
      }
    };
    text_area_blur = function() {
      var mp, tag;
      mp = $(this).parent();
      tag = this.tagName.toLowerCase();
      if (tag === "textarea") {
        if (/^\s*$/.test($(this).val())) {
          mp.parent().hide();
          return mp.parent().prev().show();
        }
      } else {
        mp.hide();
        return mp.next().show();
      }
    };
    $('.js-menu').menu();
    $('.form.small .fd > input').on('keyup', input_label);
    $('.js-paginate').paginate({
      after: function(data) {
        return $('#js_paginate_result').html(data.content);
      }
    });
    $('.js-textarea').on('keyup', text_area_key_up).on('blur', text_area_blur);
    $('.js-form-page').form({
      after: function(data) {
        $('#js_paginate_result').prepend(data.content);
        return $('.js-textarea', $(this).parent()).blur();
      }
    });
    $('.js-form-nothing').form({
      after: function(data) {
        return $('.js-textarea', $(this).parent()).blur();
      }
    });
    $('.js-form-simple input').on('focus', function() {
      text_area_blur.call(this);
      return $('.js-textarea', $(this).parent().next()).focus();
    });
    setTimeout(function() {
      return $('.form.small .fd > input').each(input_label);
    }, 500);
    $('a[rel=nofollow]').popup({
      content: function() {
        var buffer, href, method, token;
        method = this.attr('data-method');
        href = this.attr('href');
        token = $('meta[name=csrf-token]').attr('content');
        buffer = ['<form id="js_form_delete" method="post" action="', href, '">'];
        buffer.push('<input name="utf8" type="hidden" value="&#x2713;" />');
        buffer.push('<input name="authenticity_token" type="hidden" value="', token, '" />');
        buffer.push('<input type="hidden" name="_method" value="', method, '"/>');
        buffer.push('你确定要删除吗？');
        buffer.push('<button type="button" class="btn red" onclick="$(\'#js_form_delete\').submit();">确定</button>');
        buffer.push('</form>');
        return buffer.join('');
      }
    });
    return false;
  });

}).call(this);
